name: Publish package to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Get last version from GitHub Packages
        id: get_last_version
        run: |
          # Abrufen der letzten Version aus GitHub Packages
          response=$(curl -s \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/orgs/<OWNER>/packages/maven/<PACKAGE_NAME>/versions)

          # Extrahieren der letzten Version (hier wird angenommen, dass das JSON-Array sortiert ist)
          last_version=$(echo $response | jq -r '.[0].name')

          echo "Last version: $last_version"
          echo "LAST_VERSION=$last_version" >> $GITHUB_ENV

      - name: Increment version
        id: increment_version
        run: |
          # Die Version (z.B. 1.0.5) aufteilen
          last_version="${{ env.LAST_VERSION }}"
          version_parts=(${last_version//./ })

          # Erhöhen der Patch-Version
          version_parts[2]=$((version_parts[2] + 1))

          # Neue Version zusammensetzen
          new_version="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}"

          echo "New version: $new_version"
          echo "NEW_VERSION=$new_version" >> $GITHUB_ENV

      - name: Set new version in build.gradle
        run: |
          sed -i "s/^version = \".*\"/version = \"${{ env.NEW_VERSION }}\"/" build.gradle

      - name: Publish package
        run: ./gradlew publish
        env:
          MAVEN_USERNAME: ${{ secrets.ACTOR }}
          MAVEN_PASSWORD: ${{ secrets.TOKEN }}
