name: Publish package verdox repo

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      REPO_USER: ${{ secrets.REPO_USER }}
      REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run tests
        run: ./gradlew test

      - name: Publish package
        run: ./gradlew publish